# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bo_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='bo_app.User')),
                ('friends_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_with', to='bo_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_being_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_being_requested', to='bo_app.User')),
                ('user_requesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting', to='bo_app.User')),
            ],
        ),
    ]
